### ISSUE TITLE
Intervals above 1000ms ?

### ISSUE THREAD

**Issue by mellson** [sononum/SOHPTimer#1]
Thanks for the great work on this timer, much appreciated.

I am having some problems using it in an application on OS X 10.10.
When I create a timer with an interval above 1000ms I get the error `thread_policy_set: (os/kern) invalid argument`

The error is in the file `so_hptimer.c` in the method `_move_pthread_to_realtime_scheduling_class`

I am too unfamiliar with the lower level API's to know if it should be possible to create timers with a value above 1000ms.

**Comment by sononum** [comment]
For timer intervals with such a long period, normal timer apis should be used.
